version: "3.9"

networks:
  algafood-network:
    driver: bridge

services:
  algafood-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    networks:
      - algafood-network
  algafood-api:
    image: brenoaraujoo/algafood-api
    command: ["/wait-for-it.sh",
              "algafood-mysql:3306",
              "-t",
              "30",
              "--",
              "java",
              "-jar",
              "api.jar"]
    ports:
      - "8080:8080"
    networks:
      - algafood-network
    environment:
      DB_HOST: algafood-mysql
    depends_on:
      - algafood-mysql


