spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}/algafood?serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: ${MYSQL_ROOT_PASSWORD:root}
  jpa:
    hibernate:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  #Habilita lançamento de exceptions NoHandlerFoundException
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  #Formata saída colorida no console
  output:
    ansi:
      enabled: ALWAYS
  #Configuração do flyway
  flyway:
    locations: classpath:db/migration, classpath:db/testdata
  #Configuração do Jackson para habilitar lançamento de exceptions conforme atributos abaixo
  jackson:
    deserialization:
      fail-on-unknown-properties: true
      fail-on-ignored-properties: true



#  datasource:
#    hikari:
#      maximum-pool-size: 5
#      minimum-idle: 3
#      idle-timeout: 10000

#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE

